FROM postgis/postgis:16-3.4

# Instala o pacote pré-compilado do pgvector diretamente do repositório oficial do PostgreSQL
RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-16-pgvector \
    && rm -rf /var/lib/apt/lists/*