FROM postgis/postgis:16-3.4

# Atualiza dependências e compila a extensão pgvector
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       ca-certificates \
       build-essential \
       git \
       postgresql-server-dev-16 \
       clang-13 \
       llvm-13 \
    && git clone --branch v0.7.0 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && cd .. \
    && rm -rf pgvector /var/lib/apt/lists/*